[package]
name = "foosvg"
version = "0.1.0"
authors = ["Jeron Aldaron Lau <jeronaldaron@gmail.com>"]
edition = "2018"

[dependencies]
png_pong = "0.8"
usvg = "0.25"
footile = "0.7"
pix = "0.13"
pointy = "0.3"
